# Generated by Django 5.0.2 on 2024-03-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0002_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='img',
        ),
    ]
