# Generated by Django 5.0.2 on 2024-03-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0003_remove_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='', upload_to='books/'),
            preserve_default=False,
        ),
    ]
